name: lume_mobile
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  
  # Libraries
  http: ^1.1.0
  google_fonts: ^6.1.0
  pbp_django_auth: ^0.4.0
  intl: ^0.20.2
  provider: ^6.1.5+1
  cupertino_icons: ^1.0.8
  provider: ^6.1.5+1
  pbp_django_auth: ^0.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  add_to_cart_animation: ^2.0.3

flutter:
  uses-material-design: true